[package]
name = "libtest"
version = "0.1.0"
authors = ["杨坡 <000111aaaim@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
